[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/it"
  to = "/it/"
  status = 301

[[redirects]]
  from = "/de"
  to = "/de/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_VERSION = "20" }
